# Generated by Django 2.2.12 on 2020-05-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quilt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('quilter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Customer')),
            ],
        ),
    ]
