# Generated by Django 2.2.12 on 2020-05-19 00:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quilttracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('createdOn', models.DateTimeField()),
                ('modifiedOn', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BattingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='price per linear inch')),
                ('applicable_date', models.DateTimeField()),
                ('createdOn', models.DateTimeField()),
                ('modifiedOn', models.DateTimeField()),
                ('batting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quilttracker.Batting')),
            ],
        ),
        migrations.CreateModel(
            name='LongArmRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=4, unique_for_date=True, validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(0.1)], verbose_name='price per square inch')),
                ('applicable_date', models.DateTimeField()),
                ('createdOn', models.DateTimeField()),
                ('modifiedOn', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerStatus',
        ),
        migrations.DeleteModel(
            name='QuiltStatus',
        ),
        migrations.AddField(
            model_name='customer',
            name='modifiedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quilt',
            name='createdOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quilt',
            name='modifiedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='createdOn',
            field=models.DateTimeField(),
        ),
    ]
