# Generated by Django 2.2.12 on 2020-05-21 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quilttracker', '0002_auto_20200518_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pantograph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='batting',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='instagram',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='quilt',
            name='attach_binding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quilt',
            name='batting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quilttracker.Batting'),
        ),
        migrations.AddField(
            model_name='quilt',
            name='feeling',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quilt',
            name='make_binding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quilt',
            name='pattern',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quilt',
            name='receivedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quilt',
            name='sms_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batting',
            name='createdOn',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='battingprice',
            name='applicable_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='battingprice',
            name='createdOn',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='createdOn',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(max_length=64, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(max_length=64, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modifiedOn',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='longarmrates',
            name='applicable_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='longarmrates',
            name='createdOn',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='quilt',
            name='createdOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quilt',
            name='modifiedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuiltImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTaken', models.DateTimeField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=64)),
                ('quilt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quilttracker.Quilt')),
            ],
        ),
        migrations.AddField(
            model_name='quilt',
            name='pantograph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quilttracker.Pantograph'),
        ),
    ]
