# Generated by Django 2.2.12 on 2020-05-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quilttracker', '0003_auto_20200521_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
