# Generated by Django 2.2.12 on 2020-06-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quilttracker', '0004_customer_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battingprice',
            name='batting',
        ),
        migrations.DeleteModel(
            name='LongArmRates',
        ),
        migrations.RemoveField(
            model_name='quiltimages',
            name='quilt',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='createdOn',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modifiedOn',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='quilt',
            name='attach_binding',
        ),
        migrations.RemoveField(
            model_name='quilt',
            name='batting',
        ),
        migrations.RemoveField(
            model_name='quilt',
            name='createdOn',
        ),
        migrations.RemoveField(
            model_name='quilt',
            name='feeling',
        ),
        migrations.RemoveField(
            model_name='quilt',
            name='length',
        ),
        migrations.RemoveField(
            model_name='quilt',
            name='make_binding',
        ),
        migrations.RemoveField(
            model_name='quilt',
            name='modifiedOn',
        ),
        migrations.RemoveField(
            model_name='quilt',
            name='pantograph',
        ),
        migrations.RemoveField(
            model_name='quilt',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='quilt',
            name='receivedOn',
        ),
        migrations.RemoveField(
            model_name='quilt',
            name='sms_updates',
        ),
        migrations.RemoveField(
            model_name='quilt',
            name='status',
        ),
        migrations.RemoveField(
            model_name='quilt',
            name='width',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Batting',
        ),
        migrations.DeleteModel(
            name='BattingPrice',
        ),
        migrations.DeleteModel(
            name='Pantograph',
        ),
        migrations.DeleteModel(
            name='QuiltImages',
        ),
    ]
